"""create one-to-many relationship between users and tasks

Revision ID: ba367392684f
Revises: 9ff99b69ca21
Create Date: 2025-09-13 13:15:36.237944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba367392684f'
down_revision: Union[str, Sequence[str], None] = '9ff99b69ca21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key('fk users task', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk users task', type_='foreignkey')

    # ### end Alembic commands ###
