[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
/(
  | \.git
  | \.mypy_cache
  | \.venv
  | __pycache__
  | alembic
  | .env
  | .env.sample
  | .gitattributes
)/
'''